version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

executors:
  node16:
    docker:
      - image: 'cimg/node:16.20-browsers'
    working_directory: ~/portfolio-ui

jobs:
  test:
    executor: node16
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: npm ci
      - run: npm test
  build:
    executor: node16
    steps:
      - checkout
      - run: npm ci
      - run:
          command: |
            npm version patch --no-git-tag-version
            npm run build
            mkdir -p artifact
            cp -R dist/portfolio-ui artifact/
      - persist_to_workspace:
          root: ~/portfolio-ui/artifact
          paths:
            - ./*
  deploy:
    executor: node16
    steps:
      - checkout
      - attach_workspace:
          at: ~/portfolio-ui/artifact
      - add_ssh_keys:
          fingerprints:
              - "36:ac:56:ab:2a:50:65:97:f3:0e:cb:de:06:55:22:47"
      - run:
          command: |
            ssh-keyscan -t ed25519 64.226.126.29 >> ~/.ssh/known_hosts
            scp -r artifact/portfolio-ui root@64.226.126.29:/home/deployment/portfolio-ui
            ssh root@64.226.126.29 "cd /home/deployment && ./deploy.sh"
  increment_version:
    executor: node16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "dc:f7:fb:77:72:e7:a9:8e:dd:29:02:f7:72:cd:9f:90"
      - run:
          command: |
            git config --global user.email "jonathan.valle78@gmail.com"
            git config --global user.name "circleci"
            npm version patch -m "Bump version to %s [skip ci]"
            git push origin master

workflows:
  test_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
      - increment_version:
          requires:
            - deploy
